require ("core.config.keymaps")
require ("core.config.options")
require ("core.config.plugins")
require ("core.config.variable")
require("core.config.screen")
require("core.config.lazyload")
require("core.config.wilder")
require("core.config.hslens")
require("core.config.coderunner")
--require("core.config.diagnostics")
